/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmDeaprtment.java
 *
 * Created on 27 Nov, 2017, 2:26:35 PM
 */
package jinaspecial;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
/**
 *
 * @author Vaibhav
 */
public class frmGatePass extends javax.swing.JFrame {

     dbConn mc=new dbConn();
     Connection con;
     Statement st;
     ResultSet rs;
 DefaultTableModel model=new DefaultTableModel();
 dbConnection db=new dbConnection();
 
    /** Creates new form frmDeaprtment */
    public frmGatePass() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtGtaePassNo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnADDMaterial = new javax.swing.JButton();
        btnUPDATE = new javax.swing.JButton();
        btnDELETE = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPo = new javax.swing.JTable();
        dtPO = new datechooser.beans.DateChooserCombo();
        cmbUnit = new javax.swing.JComboBox();
        btnADD1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtTo = new javax.swing.JTextField();
        txtQty = new javax.swing.JTextField();
        cmbItem = new javax.swing.JComboBox();
        rd1 = new javax.swing.JRadioButton();
        rd2 = new javax.swing.JRadioButton();

        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setName("jPasswordField1"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Material Gate Pass");
        setIconImages(null);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jDesktopPane1.setBackground(new java.awt.Color(240, 240, 240));
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jDesktopPane1.setMaximumSize(new java.awt.Dimension(1147483647, 2147483647));
        jDesktopPane1.setName("jDesktopPane1"); // NOI18N
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(80, 100));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel1.setText("Gate Pass No:");
        jLabel1.setName("jLabel1"); // NOI18N
        jLabel1.setBounds(10, 20, 80, 20);
        jDesktopPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 11));
        jLabel3.setText("To:");
        jLabel3.setName("jLabel3"); // NOI18N
        jLabel3.setBounds(10, 40, 60, 30);
        jDesktopPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 11));
        jLabel4.setText("Item:");
        jLabel4.setName("jLabel4"); // NOI18N
        jLabel4.setBounds(10, 80, 70, 20);
        jDesktopPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtGtaePassNo.setBackground(new java.awt.Color(255, 255, 204));
        txtGtaePassNo.setEditable(false);
        txtGtaePassNo.setName("txtGtaePassNo"); // NOI18N
        txtGtaePassNo.setBounds(90, 20, 180, 20);
        jDesktopPane1.add(txtGtaePassNo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 11));
        jLabel13.setText("Date:");
        jLabel13.setName("jLabel13"); // NOI18N
        jLabel13.setBounds(300, 20, 60, 20);
        jDesktopPane1.add(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 11));
        jLabel14.setText("Unit:");
        jLabel14.setName("jLabel14"); // NOI18N
        jLabel14.setBounds(300, 50, 70, 20);
        jDesktopPane1.add(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnADDMaterial.setFont(new java.awt.Font("Times New Roman", 1, 11));
        btnADDMaterial.setForeground(new java.awt.Color(0, 51, 255));
        btnADDMaterial.setText("ADD");
        btnADDMaterial.setName("btnADDMaterial"); // NOI18N
        btnADDMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDMaterialActionPerformed(evt);
            }
        });
        btnADDMaterial.setBounds(280, 140, 60, 21);
        jDesktopPane1.add(btnADDMaterial, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnUPDATE.setFont(new java.awt.Font("Times New Roman", 1, 11));
        btnUPDATE.setForeground(new java.awt.Color(51, 0, 255));
        btnUPDATE.setText("UPDATE");
        btnUPDATE.setName("btnUPDATE"); // NOI18N
        btnUPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUPDATEActionPerformed(evt);
            }
        });
        btnUPDATE.setBounds(250, 420, 80, 30);
        jDesktopPane1.add(btnUPDATE, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnDELETE.setFont(new java.awt.Font("Times New Roman", 1, 11));
        btnDELETE.setForeground(new java.awt.Color(255, 51, 51));
        btnDELETE.setText("DELETE");
        btnDELETE.setName("btnDELETE"); // NOI18N
        btnDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDELETEActionPerformed(evt);
            }
        });
        btnDELETE.setBounds(340, 420, 90, 30);
        jDesktopPane1.add(btnDELETE, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        tblPo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPo.setName("tblPo"); // NOI18N
        tblPo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPo);

        jScrollPane2.setBounds(10, 170, 620, 200);
        jDesktopPane1.add(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        dtPO.setCurrentView(new datechooser.view.appearance.AppearancesList("Bordered",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    dtPO.setCalendarBackground(new java.awt.Color(255, 153, 153));
    dtPO.setBounds(380, 20, 180, 20);
    jDesktopPane1.add(dtPO, javax.swing.JLayeredPane.DEFAULT_LAYER);

    cmbUnit.setName("cmbUnit"); // NOI18N
    cmbUnit.setBounds(380, 50, 180, 20);
    jDesktopPane1.add(cmbUnit, javax.swing.JLayeredPane.DEFAULT_LAYER);

    btnADD1.setFont(new java.awt.Font("Times New Roman", 1, 11));
    btnADD1.setForeground(new java.awt.Color(0, 51, 255));
    btnADD1.setText("SEND");
    btnADD1.setName("btnADD1"); // NOI18N
    btnADD1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnADD1ActionPerformed(evt);
        }
    });
    btnADD1.setBounds(160, 420, 80, 30);
    jDesktopPane1.add(btnADD1, javax.swing.JLayeredPane.DEFAULT_LAYER);

    jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 11));
    jLabel16.setText("Quantity:");
    jLabel16.setName("jLabel16"); // NOI18N
    jLabel16.setBounds(300, 80, 70, 20);
    jDesktopPane1.add(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);

    txtTo.setBackground(new java.awt.Color(255, 255, 204));
    txtTo.setName("txtTo"); // NOI18N
    txtTo.setBounds(90, 50, 180, 20);
    jDesktopPane1.add(txtTo, javax.swing.JLayeredPane.DEFAULT_LAYER);

    txtQty.setBackground(new java.awt.Color(255, 255, 204));
    txtQty.setName("txtQty"); // NOI18N
    txtQty.setBounds(380, 80, 180, 20);
    jDesktopPane1.add(txtQty, javax.swing.JLayeredPane.DEFAULT_LAYER);

    cmbItem.setEditable(true);
    cmbItem.setName("cmbItem"); // NOI18N
    cmbItem.setBounds(90, 80, 180, 20);
    jDesktopPane1.add(cmbItem, javax.swing.JLayeredPane.DEFAULT_LAYER);

    rd1.setBackground(new java.awt.Color(255, 255, 255));
    rd1.setForeground(new java.awt.Color(0, 51, 255));
    rd1.setText("Material");
    rd1.setName("rd1"); // NOI18N
    rd1.setBounds(90, 110, 80, 23);
    jDesktopPane1.add(rd1, javax.swing.JLayeredPane.DEFAULT_LAYER);

    rd2.setBackground(new java.awt.Color(255, 255, 255));
    rd2.setForeground(new java.awt.Color(0, 51, 255));
    rd2.setText("Machine");
    rd2.setName("rd2"); // NOI18N
    rd2.setBounds(170, 110, 80, 23);
    jDesktopPane1.add(rd2, javax.swing.JLayeredPane.DEFAULT_LAYER);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
            .addContainerGap())
    );

    java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
    setBounds((screenSize.width-699)/2, (screenSize.height-523)/2, 699, 523);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       try{
           
           st=db.dbConn();
        btnUPDATE.setEnabled(false);
        btnDELETE.setEnabled(false);
        tblPo.setModel(model);
        model.addColumn("Pass No.");
        model.addColumn("Date");
        model.addColumn("To");
        model.addColumn("UOM");
        model.addColumn("Item Name");
        model.addColumn("Type");  

         con=DriverManager.getConnection(mc.StrUrl,mc.StrUid,mc.StrPwd);
       Statement st=con.createStatement();
        
        ResultSet  rss=st.executeQuery("select distinct(itemname) from tblitem");
          
        while(rss.next())
        {
                cmbItem.addItem(rss.getString("itemname"));
        }
        rss.close();
        
      rss=st.executeQuery("select * from tblunit");
          
        while(rss.next())
        {
                cmbUnit.addItem(rss.getString("unit"));
        }
        rss.close();
        
        int i=0;
            rss=st.executeQuery("select max(pasno) from tblgatepass");
        while(rss.next())
        {
            String pass=rss.getString(1);
            if(pass==null){
                pass="1";
                System.out.print(pass);
                txtGtaePassNo.setText(pass);
            }
            else{
             i=Integer.parseInt(pass);
             i +=1;
             pass=String.valueOf(i);
                txtGtaePassNo.setText(pass);
        }
        }
        rss.close();
       }
               
               
       catch(Exception e){
           System.out.print(e);
       }
        
    }//GEN-LAST:event_formWindowOpened

    private void btnADD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADD1ActionPerformed
         try {
            int i;
           st=db.dbConn();          
           String type="";
           
           if(rd1.isSelected()==true){
               type="Material";
           }else if(rd2.isSelected()==true){
               type="Machine";
           }
           //con.setAutoCommit(false);
           String rec="NO";
           int recvd=0;
            String datePattern = "yyyy-M-dd";
                 SimpleDateFormat dateFormatter = new SimpleDateFormat(datePattern);
              dtPO.setDateFormat(dateFormatter);
           
           for(i = 0; i < model.getRowCount(); i++){
           try {
              st.executeUpdate("insert into tblgatepass values(null,"+ txtGtaePassNo.getText() +",'"+ dtPO.getText() +"','"+txtTo.getText()+"','"+ cmbUnit.getSelectedItem() +"','"+ cmbItem.getSelectedItem() +"',"+txtQty.getText() +",'"+type+"','"+rec+"',"+recvd+",'"+dtPO.getText()+"')");
           } catch (SQLException ex) {
               Logger.getLogger(frmGatePass.class.getName()).log(Level.SEVERE, null, ex);
           }
               }
//           if(i>0){
//               JOptionPane.showMessageDialog(rootPane, "Gate Pass Generated successfully");
//              for (int j = i; j < model.getRowCount(); j--){
//                model.removeRow(j);
//            }
//           }
          //con.commit();
           
          
            String path = new java.io.File(".").getCanonicalPath();
           String rpt=path+"\\Reports\\rptGatePass.jrxml";
         jasperReportIA ii=new jasperReportIA(rpt,txtGtaePassNo.getText(),"","","","","","");
     
          
               //con.rollback();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(frmGatePass.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(frmGatePass.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(frmGatePass.class.getName()).log(Level.SEVERE, null, ex);
        }
                
        
}//GEN-LAST:event_btnADD1ActionPerformed

    private void tblPoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPoMouseClicked
        //         int r=tblSupplier.getSelectedRow();
        //        txtID.setText(tblSupplier.getValueAt(r, 0).toString());
        //        txtCode.setText(tblSupplier.getValueAt(r, 1).toString());
        //        btnUPDATE.setEnabled(true);
        //        btnDELETE.setEnabled(true);
        //        btnADD.setEnabled(false);
}//GEN-LAST:event_tblPoMouseClicked

    private void btnDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDELETEActionPerformed
        try{
            //           con=DriverManager.getConnection(mc.StrUrl,mc.StrUid,mc.StrPwd);
            //           Statement st=con.createStatement();
            //           int i=st.executeUpdate("Delete from tblSupplier where id="+txtID.getText()+"");
            //
            //               int dialogButton = JOptionPane.YES_NO_OPTION;
            //               int dialogResult = JOptionPane.showConfirmDialog (null, "Would You Like to Delete?","Warning",dialogButton);
            //                if(dialogResult == JOptionPane.YES_OPTION){
            //                    if(i>0){
            //                   JOptionPane.showMessageDialog(rootPane, "Deleted Successfully");
            //                   display();
            //                }
            //                   else
            //                {
            //                   JOptionPane.showMessageDialog(rootPane, "Deleted Successfully");
            //                }
            //                }
            //                else if(dialogResult == JOptionPane.NO_OPTION)
            //                {
            //
            //                    btnADD.setEnabled(true);
            //                    btnUPDATE.setEnabled(false);
            //                    btnDELETE.setEnabled(false);
            //                    display();
            //                }
            
        } catch(Exception e){
            System.out.print(e);
        }
}//GEN-LAST:event_btnDELETEActionPerformed

    private void btnUPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUPDATEActionPerformed
        try{
            //           con=DriverManager.getConnection(mc.StrUrl,mc.StrUid,mc.StrPwd);
            //          Statement st=con.createStatement();
            //
            //          int i=st.executeUpdate("update tblsupplier set code='"+txtCode.getText()+"', name='"+txtName.getText()+"', ph='"+txtPhone.getText()+"', mob="+txtMobile.getText()+" "
            //                  + ", email='"+txtEmail.getText()+"', fax='"+txtFax.getText()+"', pan="+txtPAN.getText()+" "
            //                  + ", exnum="+txtExcise.getText()+", gstno='"+txtGST.getText()+"', address='"+txtAddr.getText()+"' city='"+txtCity.getText()+"'"
            //                  + ", state='"+txtState.getText()+"', pin='"+txtPin.getText()+"', country='"+txtCountry.getText()+"' bank_name='"+txtBank.getText()+"'"
            //                  + ", bank_branch='"+txtBranch.getText()+"', bank_city='"+txtBankCity.getText()+"' acc_num='"+txtAcc.getText()+"', ifsc_code='"+txtIFSC.getText()+"'   where id="+txtID.getText()+"");
            //          if(i>0){
            //              JOptionPane.showMessageDialog(rootPane, "Supplier Details Updated Successfully");
            //              display();
            //          }
            //          else
            //          {
            //                JOptionPane.showMessageDialog(rootPane, "Error in Updation");
            //          }
        } catch(Exception e){
            System.out.print(e);
        }
}//GEN-LAST:event_btnUPDATEActionPerformed

    private void btnADDMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDMaterialActionPerformed
        try {
       
            con=DriverManager.getConnection(mc.StrUrl,mc.StrUid,mc.StrPwd);
            st=con.createStatement();
            
              if (txtGtaePassNo.getText().trim().length()==0)
             {
                     JOptionPane.showMessageDialog(null,"Enter Gate Pass Number.");
                     return;  
             }
              
              if (txtTo.getText().trim().length()==0)
             {
                     JOptionPane.showMessageDialog(null,"Enter Name To Whom allocating Gate Pass");
                     return;  
             }
              
              if (dtPO.getText().trim().length()==0 )
             {
                     JOptionPane.showMessageDialog(null,"Select Gate Pass Date");
                     return;  
             }
              
//             if (cmbItem.getSelectedItem().equals("--Select Item Name--") )
//             {
//                     JOptionPane.showMessageDialog(null,"Select Item Name");
//                     return;  
//             }
//                       
//              
//                if (cmbUnit.getSelectedItem().equals("--Select UOM--") )
//             {
//                     JOptionPane.showMessageDialog(null,"Select UOM");
//                     return;  
//             }
             
               if (rd1.isSelected()==false && rd2.isSelected()==false)
             {
                     JOptionPane.showMessageDialog(null,"Select Gate Pass Type");
                     return;  
             }
              String type="";
               if(rd1.isSelected()==true){
                   type="Material";
               }
               else
               {
                   type="Machine";
               }
               tblPo.setModel(model);               
               
              
                 model.addRow(new Object[]{txtGtaePassNo.getText(),dtPO.getText(),txtTo.getText(),cmbUnit.getSelectedItem(),cmbItem.getSelectedItem(),type});
               
               
        } catch (Exception ex) {
            Logger.getLogger(frmPurchaseOrder.class.getName()).log(Level.SEVERE, null, ex);
        }                
}//GEN-LAST:event_btnADDMaterialActionPerformed

    public void display()
     {
         try{
//             model.setRowCount(0);
//             con=DriverManager.getConnection(mc.StrUrl,mc.StrUid,mc.StrPwd);
//             Statement st=con.createStatement();
//             ResultSet rs=st.executeQuery("select * from tblsupplier");
//        while(rs.next())
//        {
//            model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(5),rs.getString(6),rs.getString(8),rs.getString(10),rs.getString(16),rs.getString(19),rs.getString(20)});
//        }
         }
         catch(Exception e){
             System.out.print(e);
         }
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmGatePass().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnADD1;
    private javax.swing.JButton btnADDMaterial;
    private javax.swing.JButton btnDELETE;
    private javax.swing.JButton btnUPDATE;
    private javax.swing.JComboBox cmbItem;
    private javax.swing.JComboBox cmbUnit;
    private datechooser.beans.DateChooserCombo dtPO;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rd1;
    private javax.swing.JRadioButton rd2;
    private javax.swing.JTable tblPo;
    private javax.swing.JTextField txtGtaePassNo;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtTo;
    // End of variables declaration//GEN-END:variables
}
