/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmDeaprtment.java
 *
 * Created on 27 Nov, 2017, 2:26:35 PM
 */
package jinaspecial;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vaibhav
 */
public class frmItem extends javax.swing.JFrame {

//     dbConn mc=new dbConn();
//     Connection con;
    dbConnection db=new dbConnection();
    Statement st;
 DefaultTableModel model=new DefaultTableModel();
    /** Creates new form frmDeaprtment */
    public frmItem() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtGrn = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDepartment = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtDeptID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtItem = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txtRate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtHsn = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMinOrder = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtMaxOrder = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cmbDept = new javax.swing.JComboBox();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        cmbUnit = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        cmbTax = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        txtRack = new javax.swing.JTextField();

        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setName("jPasswordField1"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Item Master");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setText("Item Code:"); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        txtGrn.setEditable(false);
        txtGrn.setName("txtGrn"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tblDepartment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11"
            }
        ));
        tblDepartment.setName("tblDepartment"); // NOI18N
        tblDepartment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDepartmentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDepartment);

        jLabel2.setText("Item ID:");
        jLabel2.setName("jLabel2"); // NOI18N

        txtDeptID.setEditable(false);
        txtDeptID.setName("txtDeptID"); // NOI18N

        jLabel3.setText("Item Name:"); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        txtItem.setName("txtItem"); // NOI18N

        jLabel4.setText("Description:"); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        txtDesc.setColumns(20);
        txtDesc.setRows(5);
        txtDesc.setName("txtDesc"); // NOI18N
        jScrollPane2.setViewportView(txtDesc);

        jLabel5.setText("Rate:"); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        txtRate.setName("txtRate"); // NOI18N

        jLabel6.setText("HSN:"); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        txtHsn.setName("txtHsn"); // NOI18N

        jLabel7.setText("Min.Order Level:"); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        txtMinOrder.setName("txtMinOrder"); // NOI18N

        jLabel8.setText("Max.Order Level:"); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        txtMaxOrder.setName("txtMaxOrder"); // NOI18N

        jLabel10.setText("Department:"); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        cmbDept.setName("cmbDept"); // NOI18N

        btnAdd.setText("Add");
        btnAdd.setName("btnAdd"); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.setName("btnDelete"); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.setName("btnUpdate"); // NOI18N
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel11.setText("UOM:"); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        cmbUnit.setName("cmbUnit"); // NOI18N

        jLabel12.setText("Tax:"); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        cmbTax.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "5", "12", "18", "28" }));
        cmbTax.setName("cmbTax"); // NOI18N

        jLabel13.setText("Rack:");
        jLabel13.setName("jLabel13"); // NOI18N

        txtRack.setName("txtRack"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel6)
                    .addComponent(jLabel11)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel5)
                    .addComponent(jLabel13))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtRack, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(txtMinOrder, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(cmbTax, javax.swing.GroupLayout.Alignment.LEADING, 0, 229, Short.MAX_VALUE)
                            .addComponent(cmbDept, javax.swing.GroupLayout.Alignment.LEADING, 0, 229, Short.MAX_VALUE)
                            .addComponent(txtHsn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(txtRate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(cmbUnit, javax.swing.GroupLayout.Alignment.LEADING, 0, 229, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(txtItem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(txtGrn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(txtDeptID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(txtMaxOrder, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDeptID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGrn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtItem, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(cmbUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRate, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(txtHsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbTax, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMinOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtMaxOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtRack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1175)/2, (screenSize.height-662)/2, 1175, 662);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try{
           st=db.dbConn();
             
            // To add Department
            
             if (txtGrn.getText().trim().length()==0 )
            {
                    JOptionPane.showMessageDialog(null,"Enter Item GRN Number.");
                    return;  
            }
             
               if (txtItem.getText().trim().length()==0 )
            {
                    JOptionPane.showMessageDialog(null,"Enter Item Name.");
                    return;  
            }
               
              if (txtDesc.getText().trim().length()==0 )
            {
                    JOptionPane.showMessageDialog(null,"Enter Item GRN Number.");
                    return;  
            }
              
                if (txtRate.getText().trim().length()==0 )
            {
                    JOptionPane.showMessageDialog(null,"Enter Rate.");
                    return;  
            }
                
                 if (txtHsn.getText().trim().length()==0 )
            {
                    JOptionPane.showMessageDialog(null,"Enter HSN.");
                    return;  
            }
                 
                  if (txtMinOrder.getText().trim().length()==0 )
            {
                    JOptionPane.showMessageDialog(null,"Enter Min. Order Level of Item.");
                    return;  
            }
                  
                   
                  if (txtMaxOrder.getText().trim().length()==0 )
            {
                    JOptionPane.showMessageDialog(null,"Enter Max. Order Level of Item.");
                    return;  
            }
                 
                
                
                
                
               
               ResultSet rs=st.executeQuery("select * from tblitem where grrno='"+ txtGrn.getText() +"'");
               if(rs.next()){
                   JOptionPane.showMessageDialog(rootPane, "GRN number already exists");
                   txtGrn.requestFocus();
                   return;
               }
               
               rs=st.executeQuery("select * from tblitem where itemname='"+ txtItem.getText() +"'");
               if(rs.next()){
                   JOptionPane.showMessageDialog(rootPane, "Item name already exists");
                   txtItem.requestFocus();
                   return;
               }
               
               int i=st.executeUpdate("insert into tblitem values(null,'"+txtGrn.getText()+"','"+txtItem.getText()+"','"+txtDesc.getText()+"',"+txtRate.getText()+",'"+txtHsn.getText()+"','"+cmbDept.getSelectedItem()+"',"+txtMinOrder.getText()+","+txtMaxOrder.getText()+",'"+cmbUnit.getSelectedItem()+"',"+cmbTax.getSelectedItem()+",'"+txtRack.getText()+"')");

                    if(i>0)
                    {
                            JOptionPane.showMessageDialog(rootPane,"Item Added Successfully");
                            txtGrn.setText("");
                            txtGrn.setFocusable(true);
                            txtItem.setText("");
                            txtDesc.setText("");
                            txtRate.setText("");
                            txtHsn.setText("");
                            //txtMaker.setText("");
                            txtMaxOrder.setText("");
                            txtMinOrder.setText("");
                            txtRack.setText("");
                             display();

                    }
                    else
                    {
                            JOptionPane.showMessageDialog(rootPane,"Error!");
                    }
                   
        }
        catch(Exception e){
                    System.err.print(e);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try{
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
        
        //Combobox values Department
       st=db.dbConn();
        
        ResultSet rs=st.executeQuery("select distinct(department) from tbldepartment");
        while(rs.next()){
            cmbDept.addItem(rs.getString("department"));
        }
        rs.close();
        
         rs=st.executeQuery("select unit from tblunit");
          while(rs.next()){
              cmbUnit.addItem(rs.getString(1));
          }
        tblDepartment.setModel(model);
        model.addColumn("id");
        model.addColumn("Item Code");
        model.addColumn("Item Name");
        model.addColumn("Description");
        model.addColumn("HSN");       
        model.addColumn("Rate");  
        model.addColumn("Department");
        model.addColumn("Min.Ord.Lvl");
        model.addColumn("Max.Ord.Lvl");
       // model.addColumn("Make");
        model.addColumn("Rack");
        
        ResultSet rss=st.executeQuery("select max(id)+1 from tblItem");
        while(rss.next())
        {
                txtDeptID.setText(rss.getString(1));
        }
        rss.close();
       
        rss=st.executeQuery("select max(id)+1 from tblItem");
        while(rss.next())
        {
                txtGrn.setText(rss.getString(1));
        }
        rss.close();
       
        
        
        rss.close();
        display();
        }
        
        catch(Exception e){
            System.out.print(e);
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
       try{
          st=db.dbConn();
                    
          int i=st.executeUpdate("update tblitem set grrno='"+txtGrn.getText()+"', itemname='"+txtItem.getText()+"', description='"+txtDesc.getText()+"', rate="+txtRate.getText()+" "
                  + ", hsn='"+txtHsn.getText()+"', dept='"+cmbDept.getSelectedItem()+"', min_order_level="+txtMinOrder.getText()+" "
                  + ", max_order_level="+txtMaxOrder.getText()+", uom='"+cmbUnit.getSelectedItem()+"',tax='"+cmbTax.getSelectedItem()+"',rack='"+txtRack.getText()+"'  where id="+txtDeptID.getText()+"");
          if(i>0){
              JOptionPane.showMessageDialog(rootPane, "Department Updated Successfully");
              display();
          }
          else
          {
                JOptionPane.showMessageDialog(rootPane, "Error in Updation");
          }
          
          
       }
       catch(Exception e){
           System.out.print(e);
       }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblDepartmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDepartmentMouseClicked
        try {
            int r=tblDepartment.getSelectedRow();
            
            ResultSet rs=st.executeQuery("select uom,tax from tblitem where grrno='"+tblDepartment.getValueAt(r, 1).toString()+"'");
                if(rs.next()){
                  cmbUnit.setSelectedItem(rs.getString("uom")); 
                  cmbTax.setSelectedItem(rs.getString("tax"));
                }
            txtDeptID.setText(tblDepartment.getValueAt(r, 0).toString());
            txtGrn.setText(tblDepartment.getValueAt(r, 1).toString());
            txtItem.setText(tblDepartment.getValueAt(r, 2).toString());
            txtDesc.setText(tblDepartment.getValueAt(r, 3).toString());        
            txtHsn.setText(tblDepartment.getValueAt(r, 4).toString());        
            cmbDept.setSelectedItem(tblDepartment.getValueAt(r, 6).toString());
            txtRate.setText(tblDepartment.getValueAt(r, 5).toString());
            txtMinOrder.setText(tblDepartment.getValueAt(r, 7).toString());
            txtMaxOrder.setText(tblDepartment.getValueAt(r, 8).toString());
           // txtMaker.setText(tblDepartment.getValueAt(r, 9).toString());
           txtRack.setText(tblDepartment.getValueAt(r, 9).toString());
            btnUpdate.setEnabled(true);
            btnDelete.setEnabled(true);
            btnAdd.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(frmItem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblDepartmentMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try{
           st=db.dbConn();
           int i=st.executeUpdate("Delete from tblItem where id="+txtDeptID.getText()+"");
           
               int dialogButton = JOptionPane.YES_NO_OPTION;
               int dialogResult = JOptionPane.showConfirmDialog (null, "Would You Like to Delete?","Warning",dialogButton);
                if(dialogResult == JOptionPane.YES_OPTION){
                    if(i>0){
                   JOptionPane.showMessageDialog(rootPane, "Deleted Successfully");
                   display();
                }
                   else
                {
                   JOptionPane.showMessageDialog(rootPane, "Deleted Successfully");
                }
                }
                else if(dialogResult == JOptionPane.NO_OPTION)
                {
                    
                    btnAdd.setEnabled(true);
                    btnUpdate.setEnabled(false);
                    btnDelete.setEnabled(false);
                    display();
                }
              
           
          
           
        }
        catch(Exception e){
            System.out.print(e);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    public void display()
     {
         try{
             model.setRowCount(0);
             st=db.dbConn();
             ResultSet rs=st.executeQuery("select * from tblItem");
        while(rs.next())
        {
            model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(6),rs.getString(5),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(12)});
        }
         }
         catch(Exception e){
             System.out.print(e);
         }
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmItem().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cmbDept;
    private javax.swing.JComboBox cmbTax;
    private javax.swing.JComboBox cmbUnit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDepartment;
    private javax.swing.JTextField txtDeptID;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextField txtGrn;
    private javax.swing.JTextField txtHsn;
    private javax.swing.JTextField txtItem;
    private javax.swing.JTextField txtMaxOrder;
    private javax.swing.JTextField txtMinOrder;
    private javax.swing.JTextField txtRack;
    private javax.swing.JTextField txtRate;
    // End of variables declaration//GEN-END:variables
}