/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmJobOrder.java
 *
 * Created on 15 Jan, 2018, 7:40:01 PM
 */
package jinaspecial;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author Vaibhav
 */
public class frmJobOrder extends javax.swing.JFrame {

    dbConnection db=new dbConnection();
    Statement st;
    String item="";
    DefaultTableModel model=new DefaultTableModel();
    /** Creates new form frmJobOrder */
    public frmJobOrder() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtJobID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbItemName = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        dtDate = new datechooser.beans.DateChooserCombo();
        jLabel4 = new javax.swing.JLabel();
        cmbSupplierName = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txtHSN = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbItemType = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        rd1 = new javax.swing.JRadioButton();
        rd2 = new javax.swing.JRadioButton();
        rd3 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        cmbTax = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Job Report");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setText("Job Work ID:");
        jLabel1.setName("jLabel1"); // NOI18N

        txtJobID.setBackground(new java.awt.Color(204, 204, 204));
        txtJobID.setEditable(false);
        txtJobID.setName("txtJobID"); // NOI18N

        jLabel2.setText("Item :");
        jLabel2.setName("jLabel2"); // NOI18N

        cmbItemName.setBackground(new java.awt.Color(255, 255, 102));
        cmbItemName.setEditable(true);
        cmbItemName.setName("cmbItemName"); // NOI18N
        cmbItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbItemNameActionPerformed(evt);
            }
        });
        cmbItemName.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                cmbItemNameInputMethodTextChanged(evt);
            }
        });

        jLabel3.setText("Date :");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText("Supplier :");
        jLabel4.setName("jLabel4"); // NOI18N

        cmbSupplierName.setBackground(new java.awt.Color(255, 255, 102));
        cmbSupplierName.setEditable(true);
        cmbSupplierName.setName("cmbSupplierName"); // NOI18N

        jLabel5.setText("HSN/SAC :");
        jLabel5.setName("jLabel5"); // NOI18N

        txtHSN.setName("txtHSN"); // NOI18N

        jLabel6.setText("Item Type :");
        jLabel6.setName("jLabel6"); // NOI18N

        cmbItemType.setBackground(new java.awt.Color(255, 255, 102));
        cmbItemType.setEditable(true);
        cmbItemType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Machine", "Material", " " }));
        cmbItemType.setName("cmbItemType"); // NOI18N

        jLabel7.setText("Select Tax :");
        jLabel7.setName("jLabel7"); // NOI18N

        rd1.setBackground(new java.awt.Color(255, 51, 51));
        rd1.setFont(new java.awt.Font("Times New Roman", 1, 12));
        rd1.setForeground(new java.awt.Color(255, 255, 255));
        rd1.setText("SGST/CGST");
        rd1.setName("rd1"); // NOI18N

        rd2.setBackground(new java.awt.Color(255, 51, 51));
        rd2.setFont(new java.awt.Font("Times New Roman", 1, 12));
        rd2.setForeground(new java.awt.Color(255, 255, 255));
        rd2.setText("IGST");
        rd2.setName("rd2"); // NOI18N

        rd3.setBackground(new java.awt.Color(255, 51, 51));
        rd3.setFont(new java.awt.Font("Times New Roman", 1, 12));
        rd3.setForeground(new java.awt.Color(255, 255, 255));
        rd3.setText("IIGST");
        rd3.setName("rd3"); // NOI18N

        jLabel8.setText("Tax :");
        jLabel8.setName("jLabel8"); // NOI18N

        cmbTax.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "5", "12", "18", "28" }));
        cmbTax.setName("cmbTax"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl.setName("tbl"); // NOI18N
        jScrollPane1.setViewportView(tbl);

        jButton1.setText("Add");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Generate");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Amount :");
        jLabel9.setName("jLabel9"); // NOI18N

        txtAmount.setName("txtAmount"); // NOI18N

        txtTotal.setName("txtTotal"); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Total:");
        jLabel10.setName("jLabel10"); // NOI18N

        jLabel11.setText("Quantity :");
        jLabel11.setName("jLabel11"); // NOI18N

        txtQty.setName("txtQty"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                        .addGap(4, 4, 4)
                                        .addComponent(rd1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rd2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rd3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cmbSupplierName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cmbItemName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtJobID, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(44, 44, 44))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtQty, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dtDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtHSN)
                                    .addComponent(cmbItemType, 0, 178, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbTax, 0, 178, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)
                        .addComponent(txtJobID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cmbItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbItemType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rd3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rd2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rd1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(cmbTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbItemNameActionPerformed
      // st=db.dbConn();
       
    }//GEN-LAST:event_cmbItemNameActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            st=db.dbConn();
            txtJobID.setText("");
            txtAmount.setText("");
            
            tbl.setModel(model);
            model.addColumn("Sl.No");
            model.addColumn("Item Name");
            model.addColumn("Supplier Name");            
            model.addColumn("HSN");
            model.addColumn("Qty");
            model.addColumn("Item Type");
            model.addColumn("Tax Type");
            model.addColumn("Tax in %");
            model.addColumn("Amount");
            model.addColumn("Total");
             
            int j = 0;
            ResultSet rs=st.executeQuery("select max(id) from tbljob");
            while(rs.next()){
                j=rs.getInt(1);
            }
            if(j<=0){
               // String jj=String.valueOf(j);
                txtJobID.setText("1");
            }else
            {
                j = j + 1;
                 String jj=String.valueOf(j);
                 txtJobID.setText(jj);
            }
            rs.close();
            
            //Fetching Supplier and Item
            
            rs=st.executeQuery("select distinct(itemname) from tbljob");
            while(rs.next()){
                cmbItemName.addItem(rs.getString("itemname"));
               // cmbSupplierName.addItem(rs.getString("suppliername"));
                //cmbItemType.addItem("itemtype");
            }
            rs.close();
            
              rs=st.executeQuery("select distinct(suppliername) from tbljob");
            while(rs.next()){
                //cmbItemName.addItem(rs.getString("itemname"));
               cmbSupplierName.addItem(rs.getString("suppliername"));
                //cmbItemType.addItem("itemtype");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(frmJobOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            st=db.dbConn();
            Statement st1=db.dbConn();
            String taxtype="";
             String datePattern = "yyyy-M-dd";
                 SimpleDateFormat dateFormatter = new SimpleDateFormat(datePattern);
              dtDate.setDateFormat(dateFormatter);
            if (rd1.isSelected()==false && rd2.isSelected()==false && rd3.isSelected()==false)
             {
                     JOptionPane.showMessageDialog(null,"Select Tax Type");
                     return;  
             }
             if(rd1.isSelected()==true){
                taxtype="SGST/CGST";
            }else if(rd2.isSelected()==true){
                taxtype="IGST";
            }else{
                taxtype="IIGST";
            }
             int i;
              String rec="NO";
               int recvd=0;
            ResultSet rs=st.executeQuery("select * from tbljob where itemname='"+cmbItemName.getSelectedItem()+"' or suppliername='"+cmbSupplierName.getSelectedItem()+"' or itemtype='"+cmbItemType.getSelectedItem()+"'");
            if(rs.next()){  
                 for(i = 0; i < model.getRowCount(); i++){
               st1.executeUpdate("insert into tbljob values(null,"+txtJobID.getText()+",'"+tbl.getValueAt(i, 1) +"','"+tbl.getValueAt(i, 2)+"','"+dtDate.getText()+"','"+tbl.getValueAt(i, 3)+"','"+tbl.getValueAt(i, 6)+"',"+tbl.getValueAt(i, 7)+",'"+tbl.getValueAt(i, 5)+"',"+tbl.getValueAt(i, 8)+","+tbl.getValueAt(i, 4)+","+txtTotal.getText()+",'"+rec+"',"+recvd+",'"+dtDate.getText()+"')");
               //formWindowOpened(null);
              
                 }
                  JOptionPane.showMessageDialog(txtAmount, "JOB P.O Created Successfully");
                   if(taxtype.equals("SGST/CGST")){
              String path = new java.io.File(".").getCanonicalPath();
           String rpt=path+"\\Reports\\rptPurchaseOrder1.jrxml";
             jasperReportIA iii=new jasperReportIA(rpt,"","","",txtJobID.getText(),"","","");
            }
            else if(taxtype.equals("IGST")){
                 String path = new java.io.File(".").getCanonicalPath();
           String rpt=path+"\\Reports\\rptPurchaseOrder1.jrxml";
            jasperReportIA iii=new jasperReportIA(rpt,"","","",txtJobID.getText(),"","","");
            }
            else
            {
                String path = new java.io.File(".").getCanonicalPath();
           String rpt=path+"\\Reports\\rptPurchaseOrder1.jrxml";
            jasperReportIA iii=new jasperReportIA(rpt,"","","",txtJobID.getText(),"","","");
            }
            }
            
            else{  
                    int ii=JOptionPane.showConfirmDialog(rootPane, "Do You Want to Above Details");
                    System.out.println(ii);
                            
                 if(ii==0){
                    item=cmbItemName.getSelectedItem().toString();
                    System.out.println(item);
                      for(i = 0; i < model.getRowCount(); i++){
               st1.executeUpdate("insert into tbljob values(null,"+txtJobID.getText()+",'"+tbl.getValueAt(i, 1) +"','"+tbl.getValueAt(i, 2)+"','"+dtDate.getText()+"','"+tbl.getValueAt(i, 3)+"','"+tbl.getValueAt(i, 6)+"',"+tbl.getValueAt(i, 7)+",'"+tbl.getValueAt(i, 5)+"',"+tbl.getValueAt(i, 8)+","+tbl.getValueAt(i, 4)+","+txtTotal.getText()+",'"+rec+"',"+recvd+",'"+dtDate.getText()+"')");
                 //formWindowOpened(null);
              
                      }
                       JOptionPane.showMessageDialog(txtAmount, "JOB P.O Created Successfully");
                        if(taxtype.equals("SGST/CGST")){
              String path = new java.io.File(".").getCanonicalPath();
           String rpt=path+"\\Reports\\rptPurchaseOrder1.jrxml";
             jasperReportIA iii=new jasperReportIA(rpt,"","","",txtJobID.getText(),"","","");
            }
            else if(taxtype.equals("IGST")){
                 String path = new java.io.File(".").getCanonicalPath();
           String rpt=path+"\\Reports\\rptPurchaseOrder1.jrxml";
            jasperReportIA iii=new jasperReportIA(rpt,"","","",txtJobID.getText(),"","","");
            }
            else
            {
                String path = new java.io.File(".").getCanonicalPath();
           String rpt=path+"\\Reports\\rptPurchaseOrder1.jrxml";
            jasperReportIA iii=new jasperReportIA(rpt,"","","",txtJobID.getText(),"","","");
            }
            }
                 
                  
                 }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(frmJobOrder.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(frmJobOrder.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(frmJobOrder.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frmJobOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbItemNameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_cmbItemNameInputMethodTextChanged
        try {
            st=db.dbConn();
             ResultSet rs=st.executeQuery("select distinct(itemname) from tbljob");
                 while(rs.next()){
                    // cmbItemName.addItem(rs.getString("itemname"));
                 //   cmbSupplierName.addItem(rs.getString("suppliername"));
                   //  cmbItemType.addItem("itemtype");
                 }
        } catch (SQLException ex) {
            Logger.getLogger(frmJobOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbItemNameInputMethodTextChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        int i;
        String taxtype="";
        if (txtAmount.getText().trim().length()==0)
             {
                     JOptionPane.showMessageDialog(null,"Enter Amount.");
                     return;  
             }
          if (txtHSN.getText().trim().length()==0)
             {
                     JOptionPane.showMessageDialog(null,"Enter HSN.");
                     return;  
             }
          i=model.getRowCount();
                if(i<0 )
                {
                    i=1;
                }
                else
                {
                    i =i+1;
                }
                
                 if(rd1.isSelected()==true){
                taxtype="SGST/CGST";
            }else if(rd2.isSelected()==true){
                taxtype="IGST";
            }else{
                taxtype="IIGST";
            }
                 double amt=Double.parseDouble(txtAmount.getText());
                 double tax=Double.parseDouble(cmbTax.getSelectedItem().toString());
                 double qty=Double.parseDouble(txtQty.getText());
                 double total=(amt*qty);
                 total+=(total*tax)/100;
                 
                  double tot=0;
          model.addRow(new Object[]{i,cmbItemName.getSelectedItem(),cmbSupplierName.getSelectedItem(),txtHSN.getText(),txtQty.getText(),cmbItemType.getSelectedItem(),taxtype,cmbTax.getSelectedItem(),txtAmount.getText(),total});
          for (i = 0; i < model.getRowCount(); i++){
//                   totdis +=Double.parseDouble(model.getValueAt(i, 5).toString());
//                     tottax +=Double.parseDouble(model.getValueAt(i, 9).toString());
                     tot+= Double.parseDouble(model.getValueAt(i, 9).toString());                                                     
                }
                
                
          txtTotal.setText(String.valueOf(tot));
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmJobOrder().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbItemName;
    private javax.swing.JComboBox cmbItemType;
    private javax.swing.JComboBox cmbSupplierName;
    private javax.swing.JComboBox cmbTax;
    private datechooser.beans.DateChooserCombo dtDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rd1;
    private javax.swing.JRadioButton rd2;
    private javax.swing.JRadioButton rd3;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtHSN;
    private javax.swing.JTextField txtJobID;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
