/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmPOReport.java
 *
 * Created on 6 Jan, 2018, 3:34:53 PM
 */
package jinaspecial;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author Vaibhav
 */
public class frmPOReport extends javax.swing.JFrame {

    /** Creates new form frmPOReport */
    public frmPOReport() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPONo = new javax.swing.JTextField();
        btnPOReport = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtPONo.setName("txtPONo"); // NOI18N

        btnPOReport.setText("Submit");
        btnPOReport.setName("btnPOReport"); // NOI18N
        btnPOReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPOReportActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter P.O Number:");
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtPONo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(btnPOReport)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPONo)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addComponent(btnPOReport)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPOReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPOReportActionPerformed
        try {
            if (txtPONo.getText().trim().length()==0 )
                {
                        JOptionPane.showMessageDialog(null,"Enter P.O Number.");
                        return;  
                }
            String path = new java.io.File(".").getCanonicalPath();
               String rpt=path+"\\Reports\\rptPONew.jrxml";
             jasperReportIA ii=new jasperReportIA(rpt,"","","",txtPONo.getText(),"","","");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(frmPOReport.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(frmPOReport.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(frmPOReport.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPOReportActionPerformed

    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmPOReport().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPOReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtPONo;
    // End of variables declaration//GEN-END:variables
}
