/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmReq.java
 *
 * Created on 15 Dec, 2017, 6:12:47 PM
 */
package jinaspecial;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vaibhav
 */
public class frmReturn extends javax.swing.JFrame {
     dbConn mc=new dbConn();
    DefaultTableModel model=new DefaultTableModel();
    dbConnection db=new dbConnection();
    Statement st;
    Connection con;
    ResultSet rs;
    int sl=1;
    String rsno;
    int srn;
    /** Creates new form frmReq */
    public frmReturn(String rsno) {
        initComponents();
        this.rsno=rsno;
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtfrom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtrsno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dtrsdate = new datechooser.beans.DateChooserCombo();
        txtto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReq = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtreqqty = new javax.swing.JTextField();
        cmbItem = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtItemName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtQtyIssued = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtQtyReturned = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Jina Special: Requisiton Slip");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setText("From:");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("To:");
        jLabel2.setName("jLabel2"); // NOI18N

        txtfrom.setName("txtfrom"); // NOI18N

        jLabel3.setText("Requistion Ref.No :");
        jLabel3.setName("jLabel3"); // NOI18N

        txtrsno.setName("txtrsno"); // NOI18N

        jLabel4.setText("Return Date:");
        jLabel4.setName("jLabel4"); // NOI18N

        dtrsdate.setCurrentView(new datechooser.view.appearance.AppearancesList("Grey",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));

    txtto.setName("txtto"); // NOI18N

    jScrollPane1.setName("jScrollPane1"); // NOI18N

    tblReq.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
        },
        new String [] {
            "Title 1", "Title 2", "Title 3", "Title 4"
        }
    ));
    tblReq.setName("tblReq"); // NOI18N
    tblReq.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tblReqMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(tblReq);

    jButton1.setText("Inward");
    jButton1.setName("jButton1"); // NOI18N
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    jButton2.setText("Reset");
    jButton2.setName("jButton2"); // NOI18N

    jLabel5.setText("Qty Received:");
    jLabel5.setName("jLabel5"); // NOI18N

    txtreqqty.setName("txtreqqty"); // NOI18N

    cmbItem.setName("cmbItem"); // NOI18N

    jLabel8.setText("Item :");
    jLabel8.setName("jLabel8"); // NOI18N

    jLabel6.setText("Item Name:");
    jLabel6.setName("jLabel6"); // NOI18N

    txtItemName.setName("txtItemName"); // NOI18N

    jLabel7.setText("Qty Issued:");
    jLabel7.setName("jLabel7"); // NOI18N

    txtQtyIssued.setName("txtQtyIssued"); // NOI18N

    jLabel9.setText("Qty Returned:");
    jLabel9.setName("jLabel9"); // NOI18N

    txtQtyReturned.setName("txtQtyReturned"); // NOI18N

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addComponent(jButton1)
                    .addGap(33, 33, 33)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(165, 165, 165))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(12, 12, 12)
                            .addComponent(txtfrom))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtto)
                                .addComponent(cmbItem, 0, 186, Short.MAX_VALUE))))
                    .addGap(48, 48, 48)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addGap(31, 31, 31)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dtrsdate, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                .addComponent(txtrsno, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                            .addGap(17, 17, 17))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txtreqqty, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(534, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                    .addContainerGap())))
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(29, 29, 29)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel9)
                .addComponent(jLabel7)
                .addComponent(jLabel6))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(txtItemName)
                .addComponent(txtQtyIssued)
                .addComponent(txtQtyReturned, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
            .addContainerGap(359, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(txtfrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3)
                .addComponent(txtrsno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addComponent(dtrsdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addComponent(txtreqqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6)
                .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel7)
                .addComponent(txtQtyIssued, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel9)
                .addComponent(txtQtyReturned, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton2)
                .addComponent(jButton1))
            .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            st=db.dbConn();
          Statement  st1=db.dbConn();
            tblReq.setModel(model);
            model.addColumn("Sr.No");
            model.addColumn("Description");
            model.addColumn("Qty Issued");           
            model.addColumn("Remarks");
            st=db.dbConn();
            int i=Integer.parseInt(rsno);
            
              rs=st.executeQuery("select *  from tblreq where rsno="+rsno+"");
            
        
            while(rs.next())
            {
                srn=rs.getInt("srno");
                txtfrom.setText(rs.getString("from"));
                txtto.setText(rs.getString("to"));
                txtrsno.setText(rsno);
                dtrsdate.setText(rs.getString("rsdate"));
                String item=rs.getString("itemname");
                double qty=rs.getDouble("issuedqty");    
                String rem=rs.getString("remarks");    
                
                ResultSet rs1=st1.executeQuery("select sum(returnqty) from tblitemrecv where itemname='"+item+"' and rsno="+rsno+"");
                if(rs1.next()){
                   qty = qty - rs1.getDouble(1);               
                   
                   model.addRow(new Object[]{srn,item,qty,rem});
            }
                else
                {
                   
                   model.addRow(new Object[]{srn,item,qty,rem});
                }
            }
           // rs.close();
//            
//            rs=st.executeQuery("select max(rsno) from tblreq");
//             int rsno=0;
//            if(rs.next())
//            {
//              rsno =rs.getInt(1);
//                
//            }
//          rsno +=1;
//            txtrsno.setText(String.valueOf(rsno));
            
        } catch (SQLException ex) {
            Logger.getLogger(frmReturn.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
                        con=DriverManager.getConnection(mc.StrUrl,mc.StrUid,mc.StrPwd);
                        st=con.createStatement();
           
                        double qty=Double.parseDouble(txtQtyIssued.getText());
                        double qtyRet=Double.parseDouble(txtQtyReturned.getText());
                        
                        if(qtyRet>qty){
                            JOptionPane.showMessageDialog(rootPane, "Received quantity cannot be greater than Request quantity");
                            return;
                        }
                        
                        //qtyRet=qty - qtyRet;
             int i=st.executeUpdate("update tblstock set total_qty=total_qty+"+qtyRet+" where itemname='"+txtItemName.getText()+"'");
               int ii=st.executeUpdate("insert into tblitemrecv values(null,'"+txtfrom.getText()+"','"+txtto.getText()+"',"+txtrsno.getText()+",'"+dtrsdate.getText()+"','"+txtItemName.getText()+"',"+txtQtyReturned.getText()+")");
                        if(ii>0){
                            JOptionPane.showMessageDialog(rootPane, "Item Inwarded Successfully");
                            txtItemName.setText("");
                            txtQtyIssued.setText("");
                            txtQtyReturned.setText("");
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(rootPane, "Error in Inward");
                        }
           
        } catch (SQLException ex) {
            Logger.getLogger(frmReturn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblReqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblReqMouseClicked
        DefaultTableModel model=(DefaultTableModel)tblReq.getModel();
       int selectedRow=tblReq.getSelectedRow();
        
       String itemname=tblReq.getValueAt(selectedRow, 1).toString();
       String qty=tblReq.getValueAt(selectedRow, 2).toString();
      // String qty=tblReq.getValueAt(selectedRow, 6).toString();
       
       System.out.append(qty+" "+itemname);
        txtItemName.setText(itemname);
        txtQtyIssued.setText(qty);
//        txtord1.setText(qty);
//        
      
//        txtpen.setText(tblPo1.getValueAt(selectedRow, 11).toString());
//        double ord=(Double.parseDouble(qty))-(Double.parseDouble(txtpen.getText()));
//        String ordQty=String.valueOf(ord);
//          txtprevrec.setText(ordQty);
    }//GEN-LAST:event_tblReqMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmReturn("").setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbItem;
    private datechooser.beans.DateChooserCombo dtrsdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReq;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtQtyIssued;
    private javax.swing.JTextField txtQtyReturned;
    private javax.swing.JTextField txtfrom;
    private javax.swing.JTextField txtreqqty;
    private javax.swing.JTextField txtrsno;
    private javax.swing.JTextField txtto;
    // End of variables declaration//GEN-END:variables
}
