/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmDeaprtment.java
 *
 * Created on 27 Nov, 2017, 2:26:35 PM
 */

package jinaspecial;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vaibhav
 */
public class frmSupplier extends javax.swing.JFrame {

     dbConn mc=new dbConn();
     dbConnection db=new dbConnection();
     Connection con;
     Statement st;
     ResultSet rs;
 DefaultTableModel model=new DefaultTableModel();
    /** Creates new form frmDeaprtment */
    public frmSupplier() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMobile = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFax = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPAN = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtGST = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddr = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        txtPin = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtCountry = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtBank = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtBranch = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtBankCity = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtAcc = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtIFSC = new javax.swing.JTextField();
        btnADD = new javax.swing.JButton();
        btnUPDATE = new javax.swing.JButton();
        btnDELETE = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSupplier = new javax.swing.JTable();

        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setName("jPasswordField1"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Supplier Master");
        setIconImages(null);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jDesktopPane1.setBackground(new java.awt.Color(240, 240, 240));
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jDesktopPane1.setMaximumSize(new java.awt.Dimension(1147483647, 2147483647));
        jDesktopPane1.setName("jDesktopPane1"); // NOI18N
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(80, 100));
        jDesktopPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDesktopPane1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel1.setText("ID:");
        jLabel1.setName("jLabel1"); // NOI18N
        jLabel1.setBounds(10, 30, 20, 14);
        jDesktopPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtID.setBackground(new java.awt.Color(240, 240, 240));
        txtID.setEditable(false);
        txtID.setName("txtID"); // NOI18N
        txtID.setBounds(90, 30, 180, 20);
        jDesktopPane1.add(txtID, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 11));
        jLabel2.setText("Code:");
        jLabel2.setName("jLabel2"); // NOI18N
        jLabel2.setBounds(5, 60, 60, 13);
        jDesktopPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtCode.setBackground(new java.awt.Color(255, 255, 204));
        txtCode.setName("txtCode"); // NOI18N
        txtCode.setBounds(90, 60, 180, 20);
        jDesktopPane1.add(txtCode, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 11));
        jLabel3.setText("Name:");
        jLabel3.setName("jLabel3"); // NOI18N
        jLabel3.setBounds(5, 90, 40, 13);
        jDesktopPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtName.setBackground(new java.awt.Color(255, 255, 204));
        txtName.setName("txtName"); // NOI18N
        txtName.setBounds(90, 90, 180, 20);
        jDesktopPane1.add(txtName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 11));
        jLabel4.setText("Phone:");
        jLabel4.setName("jLabel4"); // NOI18N
        jLabel4.setBounds(5, 120, 50, 13);
        jDesktopPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtPhone.setBackground(new java.awt.Color(255, 255, 204));
        txtPhone.setName("txtPhone"); // NOI18N
        txtPhone.setBounds(90, 120, 180, 20);
        jDesktopPane1.add(txtPhone, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 11));
        jLabel5.setText("Mobile:");
        jLabel5.setName("jLabel5"); // NOI18N
        jLabel5.setBounds(10, 150, 40, 20);
        jDesktopPane1.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtMobile.setBackground(new java.awt.Color(255, 255, 204));
        txtMobile.setName("txtMobile"); // NOI18N
        txtMobile.setBounds(90, 150, 180, 20);
        jDesktopPane1.add(txtMobile, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 11));
        jLabel6.setText("E-Mail:");
        jLabel6.setName("jLabel6"); // NOI18N
        jLabel6.setBounds(10, 180, 40, 20);
        jDesktopPane1.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtEmail.setBackground(new java.awt.Color(255, 255, 204));
        txtEmail.setName("txtEmail"); // NOI18N
        txtEmail.setBounds(90, 180, 180, 20);
        jDesktopPane1.add(txtEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 11));
        jLabel7.setText("Fax:");
        jLabel7.setName("jLabel7"); // NOI18N
        jLabel7.setBounds(10, 210, 40, 20);
        jDesktopPane1.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtFax.setBackground(new java.awt.Color(255, 255, 204));
        txtFax.setName("txtFax"); // NOI18N
        txtFax.setBounds(90, 210, 180, 20);
        jDesktopPane1.add(txtFax, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 11));
        jLabel8.setText("PAN No:");
        jLabel8.setName("jLabel8"); // NOI18N
        jLabel8.setBounds(10, 240, 50, 20);
        jDesktopPane1.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtPAN.setBackground(new java.awt.Color(255, 255, 204));
        txtPAN.setName("txtPAN"); // NOI18N
        txtPAN.setBounds(90, 240, 180, 20);
        jDesktopPane1.add(txtPAN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 11));
        jLabel10.setText("GST No:");
        jLabel10.setName("jLabel10"); // NOI18N
        jLabel10.setBounds(10, 270, 60, 20);
        jDesktopPane1.add(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtGST.setBackground(new java.awt.Color(255, 255, 204));
        txtGST.setName("txtGST"); // NOI18N
        txtGST.setBounds(90, 270, 180, 20);
        jDesktopPane1.add(txtGST, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 11));
        jLabel11.setText("Address:");
        jLabel11.setName("jLabel11"); // NOI18N
        jLabel11.setBounds(10, 300, 60, 20);
        jDesktopPane1.add(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        txtAddr.setBackground(new java.awt.Color(255, 255, 153));
        txtAddr.setColumns(20);
        txtAddr.setRows(5);
        txtAddr.setName("txtAddr"); // NOI18N
        jScrollPane1.setViewportView(txtAddr);

        jScrollPane1.setBounds(90, 300, 180, 70);
        jDesktopPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 11));
        jLabel12.setText("City:");
        jLabel12.setName("jLabel12"); // NOI18N
        jLabel12.setBounds(300, 30, 50, 20);
        jDesktopPane1.add(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtCity.setBackground(new java.awt.Color(255, 255, 204));
        txtCity.setName("txtCity"); // NOI18N
        txtCity.setBounds(390, 30, 180, 20);
        jDesktopPane1.add(txtCity, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 11));
        jLabel13.setText("State:");
        jLabel13.setName("jLabel13"); // NOI18N
        jLabel13.setBounds(300, 60, 60, 20);
        jDesktopPane1.add(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtState.setBackground(new java.awt.Color(255, 255, 204));
        txtState.setName("txtState"); // NOI18N
        txtState.setBounds(390, 60, 180, 20);
        jDesktopPane1.add(txtState, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtPin.setBackground(new java.awt.Color(255, 255, 204));
        txtPin.setName("txtPin"); // NOI18N
        txtPin.setBounds(390, 90, 180, 20);
        jDesktopPane1.add(txtPin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 11));
        jLabel14.setText("Pin Code:");
        jLabel14.setName("jLabel14"); // NOI18N
        jLabel14.setBounds(300, 90, 60, 20);
        jDesktopPane1.add(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtCountry.setBackground(new java.awt.Color(255, 255, 204));
        txtCountry.setName("txtCountry"); // NOI18N
        txtCountry.setBounds(390, 120, 180, 20);
        jDesktopPane1.add(txtCountry, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 11));
        jLabel15.setText("Country:");
        jLabel15.setName("jLabel15"); // NOI18N
        jLabel15.setBounds(300, 120, 60, 20);
        jDesktopPane1.add(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtBank.setBackground(new java.awt.Color(255, 255, 204));
        txtBank.setName("txtBank"); // NOI18N
        txtBank.setBounds(390, 150, 180, 20);
        jDesktopPane1.add(txtBank, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 11));
        jLabel16.setText("Bank Name:");
        jLabel16.setName("jLabel16"); // NOI18N
        jLabel16.setBounds(300, 150, 70, 20);
        jDesktopPane1.add(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtBranch.setBackground(new java.awt.Color(255, 255, 204));
        txtBranch.setName("txtBranch"); // NOI18N
        txtBranch.setBounds(390, 180, 180, 20);
        jDesktopPane1.add(txtBranch, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 11));
        jLabel17.setText("Branch:");
        jLabel17.setName("jLabel17"); // NOI18N
        jLabel17.setBounds(300, 180, 60, 20);
        jDesktopPane1.add(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel18.setText("Branch City:");
        jLabel18.setName("jLabel18"); // NOI18N
        jLabel18.setBounds(300, 210, 70, 20);
        jDesktopPane1.add(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtBankCity.setBackground(new java.awt.Color(255, 255, 204));
        txtBankCity.setName("txtBankCity"); // NOI18N
        txtBankCity.setBounds(390, 210, 180, 20);
        jDesktopPane1.add(txtBankCity, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 11));
        jLabel19.setText("Account No:");
        jLabel19.setName("jLabel19"); // NOI18N
        jLabel19.setBounds(300, 240, 70, 20);
        jDesktopPane1.add(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtAcc.setBackground(new java.awt.Color(255, 255, 204));
        txtAcc.setName("txtAcc"); // NOI18N
        txtAcc.setBounds(390, 240, 180, 20);
        jDesktopPane1.add(txtAcc, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 11));
        jLabel20.setText("IFSC Code:");
        jLabel20.setName("jLabel20"); // NOI18N
        jLabel20.setBounds(300, 270, 60, 20);
        jDesktopPane1.add(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtIFSC.setBackground(new java.awt.Color(255, 255, 204));
        txtIFSC.setName("txtIFSC"); // NOI18N
        txtIFSC.setBounds(390, 270, 180, 20);
        jDesktopPane1.add(txtIFSC, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnADD.setFont(new java.awt.Font("Times New Roman", 1, 11));
        btnADD.setForeground(new java.awt.Color(0, 51, 255));
        btnADD.setText("ADD");
        btnADD.setName("btnADD"); // NOI18N
        btnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDActionPerformed(evt);
            }
        });
        btnADD.setBounds(320, 380, 60, 21);
        jDesktopPane1.add(btnADD, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnUPDATE.setFont(new java.awt.Font("Times New Roman", 1, 11));
        btnUPDATE.setForeground(new java.awt.Color(51, 0, 255));
        btnUPDATE.setText("UPDATE");
        btnUPDATE.setName("btnUPDATE"); // NOI18N
        btnUPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUPDATEActionPerformed(evt);
            }
        });
        btnUPDATE.setBounds(391, 380, 80, 21);
        jDesktopPane1.add(btnUPDATE, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnDELETE.setFont(new java.awt.Font("Times New Roman", 1, 11));
        btnDELETE.setForeground(new java.awt.Color(255, 51, 51));
        btnDELETE.setText("DELETE");
        btnDELETE.setName("btnDELETE"); // NOI18N
        btnDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDELETEActionPerformed(evt);
            }
        });
        btnDELETE.setBounds(480, 380, 90, 21);
        jDesktopPane1.add(btnDELETE, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        tblSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSupplier.setName("tblSupplier"); // NOI18N
        tblSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSupplierMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSupplier);

        jScrollPane2.setBounds(10, 410, 640, 140);
        jDesktopPane1.add(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-705)/2, (screenSize.height-621)/2, 705, 621);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       try{
        btnUPDATE.setEnabled(false);
        btnDELETE.setEnabled(false);
        tblSupplier.setModel(model);
        model.addColumn("id");
        model.addColumn("Code");
        model.addColumn("Name");
        model.addColumn("Mobile");
        model.addColumn("Email");       
        model.addColumn("PAN No");  
        model.addColumn("GST NO");
        model.addColumn("Bank Name");
        model.addColumn("Acc.No");
        model.addColumn("IFSC Code");
        
//        ResultSet rss=st.executeQuery("select max(id) from tblSupplier");
//        while(rss.next())
//        {
//                txtID.setText(rss.getString(1));
//        }
        display();
       }               
               
       catch(Exception e){
           System.out.print(e);
       }
        
    }//GEN-LAST:event_formWindowOpened

    private void btnADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDActionPerformed
       try{
           con=DriverManager.getConnection(mc.StrUrl,mc.StrUid,mc.StrPwd);
           st=con.createStatement();           
           
             if (txtCode.getText().trim().length()==0)
            {
                    JOptionPane.showMessageDialog(null,"Enter Supplier Code.");
                    return;  
            }
             
             if (txtName.getText().trim().length()==0)
            {
                    JOptionPane.showMessageDialog(null,"Enter Supplier Name.");
                    return;  
            }
             
             if (txtPhone.getText().trim().length()==0 || txtMobile.getText().trim().length()==0 || txtFax.getText().trim().length()==0)
            {
                    JOptionPane.showMessageDialog(null,"Enter Supplier Required Contact Details.");
                    return;  
            }
                         
             if (txtAddr.getText().trim().length()==0 || txtCity.getText().trim().length()==0 || txtState.getText().trim().length()==0)
            {
                    JOptionPane.showMessageDialog(null,"Enter Complete Address Details.");
                    return;  
            } 
                         
             if (txtBank.getText().trim().length()==0 || txtBranch.getText().trim().length()==0 || txtBankCity.getText().trim().length()==0)
            {
                    JOptionPane.showMessageDialog(null,"Enter Complete Bank Address Details.");
                    return;  
            } 
             
             if (txtAcc.getText().trim().length()==0 || txtIFSC.getText().trim().length()==0 )
            {
                    JOptionPane.showMessageDialog(null,"Enter Bank Account no & IFSC code.");
                    return;  
            } 
             
              String word = txtAcc.getText();
                Pattern pattern = Pattern.compile("[0-9]+");
                Matcher matcher = pattern.matcher(word);
               if (!matcher.matches()) {
                    JOptionPane.showMessageDialog(rootPane,"Account Number should be in digits");
                      txtAcc.setText("");
                      txtAcc.setFocusable(true);
                      return;
                }
             
           rs=st.executeQuery("select * from tblsupplier where code='"+txtCode.getText()+"'");
           if(rs.next())
           {
               JOptionPane.showMessageDialog(rootPane, "Supplier Record All ready exists");
           }
           else{
               //Supplier Record Insert
               
           int i=st.executeUpdate("insert into tblsupplier values(null,'"+txtCode.getText()+"','"+txtName.getText()+"','"+txtPhone.getText()+"','"+txtMobile.getText()+"','"+txtEmail.getText()+"','"+txtFax.getText()+"','"+txtPAN.getText()+"','"+txtGST.getText()+"','"+txtAddr.getText()+"','"+txtCity.getText()+"','"+txtState.getText()+"','"+txtPin.getText()+"','"+txtCountry.getText()+"', '"+txtBank.getText()+"', '"+txtBranch.getText()+"', '"+txtBankCity.getText()+"', '"+txtAcc.getText()+"', '"+txtIFSC.getText()+"')");
           
               if(i>0)
               {
                   JOptionPane.showMessageDialog(rootPane, "Supplier Record Added Successfully");
                   display();
               }
               else{
                   JOptionPane.showMessageDialog(rootPane, "Record Not Inserted!Error in insertion");
               }
             }
       }
       catch(Exception e){
           System.out.print(e);
       }
    }//GEN-LAST:event_btnADDActionPerformed

    private void tblSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSupplierMouseClicked
        try {
            int r=tblSupplier.getSelectedRow();
            txtID.setText(tblSupplier.getValueAt(r, 0).toString());
                    
            st=db.dbConn();
            
            rs=st.executeQuery("select * from tblsupplier where id="+ txtID.getText());
            if(rs.next()){
                txtCode.setText(rs.getString(2));
                txtName.setText(rs.getString(3));
                txtPhone.setText(rs.getString(4));
                txtMobile.setText(rs.getString(5));
                txtEmail.setText(rs.getString(6));
                txtFax.setText(rs.getString(7));
                txtPAN.setText(rs.getString(8));
                txtGST.setText(rs.getString(9));
                txtAddr.setText(rs.getString(10));
                txtCity.setText(rs.getString(11));
                txtState.setText(rs.getString(12));
                txtPin.setText(rs.getString(13));
                txtCountry.setText(rs.getString(14));
                txtBank.setText(rs.getString(15));
                txtBranch.setText(rs.getString(16));
                txtBankCity.setText(rs.getString(17));
                txtAcc.setText(rs.getString(18));
                txtIFSC.setText(rs.getString(19));
            }
            
            btnUPDATE.setEnabled(true);
            btnDELETE.setEnabled(true);
            btnADD.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(frmSupplier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblSupplierMouseClicked

    private void btnUPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUPDATEActionPerformed
        try{
           con=DriverManager.getConnection(mc.StrUrl,mc.StrUid,mc.StrPwd);
          Statement st=con.createStatement();
          
          int i=st.executeUpdate("update tblsupplier set code='"+txtCode.getText()+"', name='"+txtName.getText()+"', ph='"+txtPhone.getText()+"', mob="+txtMobile.getText()+" "
                  + ", email='"+txtEmail.getText()+"', fax='"+txtFax.getText()+"', pan='"+txtPAN.getText()+"'"
                  + ", gstno='"+txtGST.getText()+"', address='"+txtAddr.getText()+"', city='"+txtCity.getText()+"'"
                  + ", state='"+txtState.getText()+"', pin='"+txtPin.getText()+"', country='"+txtCountry.getText()+"', bank_name='"+txtBank.getText()+"'"
                  + ", bank_branch='"+txtBranch.getText()+"', bank_city='"+txtBankCity.getText()+"', acc_num='"+txtAcc.getText()+"', ifsc_code='"+txtIFSC.getText()+"'   where id="+txtID.getText()+"");
          if(i>0){
              JOptionPane.showMessageDialog(rootPane, "Supplier Details Updated Successfully");
              display();
          }
          else
          {
                JOptionPane.showMessageDialog(rootPane, "Error in Updation");
          }
       }
       catch(Exception e){
           System.out.println(e);
       }
    }//GEN-LAST:event_btnUPDATEActionPerformed

    private void btnDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDELETEActionPerformed
        try{
           con=DriverManager.getConnection(mc.StrUrl,mc.StrUid,mc.StrPwd);
           Statement st=con.createStatement();           
           
               int dialogButton = JOptionPane.YES_NO_OPTION;
               int dialogResult = JOptionPane.showConfirmDialog (null, "Would You Like to Delete?","Warning",dialogButton);
                if(dialogResult == JOptionPane.YES_OPTION){
                    int i=st.executeUpdate("Delete from tblSupplier where id="+txtID.getText()+"");
                    if(i>0){
                   JOptionPane.showMessageDialog(rootPane, "Deleted Successfully");
                   display();
                }
                   else
                {
                   JOptionPane.showMessageDialog(rootPane, "Deleted Successfully");
                }
                }
                else if(dialogResult == JOptionPane.NO_OPTION)
                {
                    
                    btnADD.setEnabled(true);
                    btnUPDATE.setEnabled(false);
                    btnDELETE.setEnabled(false);
                    display();
                }
              
        }
        catch(Exception e){
            System.out.print(e);
        }
          
    }//GEN-LAST:event_btnDELETEActionPerformed

    private void jDesktopPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDesktopPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jDesktopPane1MouseClicked

    public void display()
     {
         try{
             model.setRowCount(0);
             con=DriverManager.getConnection(mc.StrUrl,mc.StrUid,mc.StrPwd);
             Statement st=con.createStatement();
             ResultSet rs=st.executeQuery("select * from tblsupplier");
        while(rs.next())
        {
            model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(5),rs.getString(6),rs.getString(8),rs.getString(9),rs.getString(15),rs.getString(18),rs.getString(19)});
        }
         }
         catch(Exception e){
             System.out.print(e);
         }
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmSupplier().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnADD;
    private javax.swing.JButton btnDELETE;
    private javax.swing.JButton btnUPDATE;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblSupplier;
    private javax.swing.JTextField txtAcc;
    private javax.swing.JTextArea txtAddr;
    private javax.swing.JTextField txtBank;
    private javax.swing.JTextField txtBankCity;
    private javax.swing.JTextField txtBranch;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtGST;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtIFSC;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPAN;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPin;
    private javax.swing.JTextField txtState;
    // End of variables declaration//GEN-END:variables
}
