/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Login.java
 *
 * Created on Sep 25, 2017, 5:59:59 PM
 */
package jinaspecial;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Vaibhav
 */
public class Login extends javax.swing.JFrame {

    /** Creates new form Login */
    public Login() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TxtUserName = new javax.swing.JTextField();
        TxtPassword = new javax.swing.JPasswordField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(0, 102, 255));
        setBounds(new java.awt.Rectangle(300, 60, 0, 0));

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14));
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Login Portal");

        jLayeredPane3.setBackground(new java.awt.Color(255, 255, 204));
        jLayeredPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Dialog 12", 1, 12));
        jLabel8.setText("User Name              :");
        jLabel8.setBounds(30, 20, 110, 16);
        jLayeredPane3.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel9.setFont(new java.awt.Font("Dialog 12", 1, 12));
        jLabel9.setText("Password               :");
        jLabel9.setBounds(30, 60, 110, 16);
        jLayeredPane3.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        TxtUserName.setFont(new java.awt.Font("Tahoma 12", 1, 12));
        TxtUserName.setForeground(new java.awt.Color(0, 51, 255));
        TxtUserName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtUserName.setBounds(150, 20, 190, 20);
        jLayeredPane3.add(TxtUserName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        TxtPassword.setFont(new java.awt.Font("Tahoma 12", 1, 12));
        TxtPassword.setForeground(new java.awt.Color(0, 51, 153));
        TxtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtPassword.setBounds(150, 60, 190, 20);
        jLayeredPane3.add(TxtPassword, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton5.setFont(new java.awt.Font("Dialog 14", 1, 12));
        jButton5.setText("Login");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.setBounds(90, 110, 90, 30);
        jLayeredPane3.add(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton6.setFont(new java.awt.Font("Dialog 14", 1, 12));
        jButton6.setText("Cancel");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jButton6.setBounds(220, 110, 90, 30);
        jLayeredPane3.add(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel3)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            String stru="";
            stru=TxtUserName.getText();
            
            String strp="";
            strp=TxtPassword.getText();
            if (stru.isEmpty()==true) {
                JOptionPane.showMessageDialog(null,"Enter User Name");
                return;
            }
            
            if (strp.isEmpty()==true) {
                JOptionPane.showMessageDialog(null,"Enter Password");
                return;
            }
            //get database connection details
             dbConn mc =new dbConn();
            String a="",b="",n="",m="";
            //open connection
            Connection connection;
            connection=DriverManager.getConnection(mc.StrUrl,mc.StrUid,mc.StrPwd);
            String str="";
            str="select * from tbluser where user_name =? and user_password =?";
            PreparedStatement pst=connection.prepareStatement(str);
            pst.setString(1, stru);
            pst.setString(2, strp);
            ResultSet rs;
            rs=pst.executeQuery();
            a=TxtUserName.getText();
            b=TxtPassword.getText();
            while(rs.next()) {
                m=rs.getString(1);
                n=rs.getString(2);
            }
            if(a.equals(m) && b.equals(n)) {
                dbConn.StrUser=TxtUserName.getText();
                mainForm f=new mainForm();
                f.setVisible(true);
                this.dispose();
                return;
            } else {
                JOptionPane.showMessageDialog(rootPane, "Invalid User Name/Password", "Login", 0);
                TxtUserName.setText("");
                TxtPassword.setText("");
                TxtUserName.requestFocus();
                return;
            }
            
        }catch (Exception e) {
            System.out.println(e);
            //System.exit(1);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        System.exit(1);
}//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField TxtPassword;
    private javax.swing.JTextField TxtUserName;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}